- page: home
  path: /
  title: vis.gl - Urban Computing Foundation
  meta:
    - item:
      name: description
      content: Cutting edge technology meets beautiful data visualization.
    - item:
      name: keywords
      content: visualization, data visualization, webGL, UCF
- page: about
  path: /about
  title: About vis.gl
  meta:
    - item:
      name: description
      content: Join an open team of software engineers, information designers, and computer graphics specialists.
    - item:
      name: keywords
      content: UCF, visualization, engineering 
- page: news
  path: /news
  title: vis.gl in the news
  meta:
    - item:
      name: description
      content: Learn more about how our work is creating impact
    - item:
      name: keywords
      content: UCF, visualization, engineering, events, meetups, articles
- page: showcases
  path: /showcases
  title: vis.gl showcase
- page: blog
  path: /blog
  title: Blog posts about vis.gl
- page: frameworks
  path: /frameworks
  title: Frameworks of vis.gl
